// Code generated by mockery v2.49.0. DO NOT EDIT.

package pullrequest

import (
	context "context"

	github "github.com/google/go-github/v50/github"
	id "github.com/marqeta/pr-bot/id"

	mock "github.com/stretchr/testify/mock"
)

// MockEventHandler is an autogenerated mock type for the EventHandler type
type MockEventHandler struct {
	mock.Mock
}

type MockEventHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventHandler) EXPECT() *MockEventHandler_Expecter {
	return &MockEventHandler_Expecter{mock: &_m.Mock}
}

// EvalAndReview provides a mock function with given fields: ctx, _a1, event
func (_m *MockEventHandler) EvalAndReview(ctx context.Context, _a1 id.PR, event *github.PullRequestEvent) error {
	ret := _m.Called(ctx, _a1, event)

	if len(ret) == 0 {
		panic("no return value specified for EvalAndReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, id.PR, *github.PullRequestEvent) error); ok {
		r0 = rf(ctx, _a1, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventHandler_EvalAndReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalAndReview'
type MockEventHandler_EvalAndReview_Call struct {
	*mock.Call
}

// EvalAndReview is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 id.PR
//   - event *github.PullRequestEvent
func (_e *MockEventHandler_Expecter) EvalAndReview(ctx interface{}, _a1 interface{}, event interface{}) *MockEventHandler_EvalAndReview_Call {
	return &MockEventHandler_EvalAndReview_Call{Call: _e.mock.On("EvalAndReview", ctx, _a1, event)}
}

func (_c *MockEventHandler_EvalAndReview_Call) Run(run func(ctx context.Context, _a1 id.PR, event *github.PullRequestEvent)) *MockEventHandler_EvalAndReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(id.PR), args[2].(*github.PullRequestEvent))
	})
	return _c
}

func (_c *MockEventHandler_EvalAndReview_Call) Return(_a0 error) *MockEventHandler_EvalAndReview_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventHandler_EvalAndReview_Call) RunAndReturn(run func(context.Context, id.PR, *github.PullRequestEvent) error) *MockEventHandler_EvalAndReview_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventHandler creates a new instance of MockEventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventHandler {
	mock := &MockEventHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
