// Code generated by mockery v2.49.0. DO NOT EDIT.

package rate

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockLimiter is an autogenerated mock type for the Limiter type
type MockLimiter struct {
	mock.Mock
}

type MockLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimiter) EXPECT() *MockLimiter_Expecter {
	return &MockLimiter_Expecter{mock: &_m.Mock}
}

// Limit provides a mock function with given fields: ctx
func (_m *MockLimiter) Limit(ctx context.Context) (time.Duration, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Limit")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (time.Duration, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) time.Duration); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLimiter_Limit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Limit'
type MockLimiter_Limit_Call struct {
	*mock.Call
}

// Limit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLimiter_Expecter) Limit(ctx interface{}) *MockLimiter_Limit_Call {
	return &MockLimiter_Limit_Call{Call: _e.mock.On("Limit", ctx)}
}

func (_c *MockLimiter_Limit_Call) Run(run func(ctx context.Context)) *MockLimiter_Limit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLimiter_Limit_Call) Return(_a0 time.Duration, _a1 error) *MockLimiter_Limit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLimiter_Limit_Call) RunAndReturn(run func(context.Context) (time.Duration, error)) *MockLimiter_Limit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLimiter creates a new instance of MockLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimiter {
	mock := &MockLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
