// Code generated by mockery v2.33.0. DO NOT EDIT.

package secrets

import (
	context "context"

	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	mock "github.com/stretchr/testify/mock"
)

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

type MockAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPI) EXPECT() *MockAPI_Expecter {
	return &MockAPI_Expecter{mock: &_m.Mock}
}

// GetSecretValue provides a mock function with given fields: ctx, params, optFns
func (_m *MockAPI) GetSecretValue(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *secretsmanager.GetSecretValueOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) *secretsmanager.GetSecretValueOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.GetSecretValueOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPI_GetSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretValue'
type MockAPI_GetSecretValue_Call struct {
	*mock.Call
}

// GetSecretValue is a helper method to define mock.On call
//   - ctx context.Context
//   - params *secretsmanager.GetSecretValueInput
//   - optFns ...func(*secretsmanager.Options)
func (_e *MockAPI_Expecter) GetSecretValue(ctx interface{}, params interface{}, optFns ...interface{}) *MockAPI_GetSecretValue_Call {
	return &MockAPI_GetSecretValue_Call{Call: _e.mock.On("GetSecretValue",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockAPI_GetSecretValue_Call) Run(run func(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options))) *MockAPI_GetSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*secretsmanager.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*secretsmanager.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*secretsmanager.GetSecretValueInput), variadicArgs...)
	})
	return _c
}

func (_c *MockAPI_GetSecretValue_Call) Return(_a0 *secretsmanager.GetSecretValueOutput, _a1 error) *MockAPI_GetSecretValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPI_GetSecretValue_Call) RunAndReturn(run func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)) *MockAPI_GetSecretValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPI creates a new instance of MockAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPI {
	mock := &MockAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
